name: nerfRenderer
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pytorch::pytorch
  - pytorch::torchvision
  - cudatoolkit=11.3
  - imageio
  - ninja
  - tensorboard
  - tqdm
  - pip
  - pip:
    - dacite
    - einops
    - open3d
    - pyyaml
    - tabulate
    - torchtyping
