x_enc_count: 10
d_enc_count: 4
x_layers: 8
d_layers: 2
x_widths: 256
d_widths: [256, 128]
x_skips: [5]
activation: relu
network_seed: 80000
num_samples_per_ray: 384
pts_bsize: 2000000
pixels_bsize: 400000
ert_bsize: 8
ert_trans_thres: 0.01
