num_rays_per_batch: 1024
precrop_fraction: 0.5
precrop_iterations: 0
initial_learning_rate: 0.0005
learning_rate_decay: 0
num_iterations: 200000
test_skip: 1
distill: null
intervals:
  print: 100
  log: 100
  ckpt: 10000
  test: 10000
rng_seed: 69420
