num_rays_per_batch: 4096
defer_patch_size: 200
precrop_fraction: 0.5
precrop_iterations: 0
initial_learning_rate: 0.01
learning_rate_decay: 30000
max_eval_count: 20
num_iterations: 30000
test_before_train: false
intervals:
  print: 100
  log: 100
  ckpt: 5000
  test: 5000
rng_seed: 69420
enable_amp: true
ema_decay: 0.95
sparsity_lambda: 0.0
sparsity_exp_coeff: 0.05
sparsity_samples: 50000
weight_reg_lambda: 0.0
content_lambda: 0.025
style_lambda: 0.1
photo_lambda: 0.0001
