num_rays_per_batch: 1024
precrop_fraction: 0.5
precrop_iterations: 0
initial_learning_rate: 0.0005
learning_rate_decay: 0
num_iterations: 200000
test_skip: 1
test_before_train: false
distill: null
intervals:
  print: 100
  log: 100
  ckpt: 10000
  test: 20000
rng_seed: 69420
sparsity_lambda: 0
sparsity_bbox_scale: 2.0
sparsity_exp_coeff: 0.05
sparsity_samples: 50000
content_lambda: 0.025
style_lambda: 0.1
photo_lambda: 0.0001
